const image = [
    {
        id:1,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:2,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:3,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:4,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:5,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:6,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:7,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:8,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:9,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:10,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:11,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:12,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:13,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:14,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:15,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:16,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:17,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:18,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:19,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:20,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:21,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:22,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:23,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:24,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:25,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:26,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:27,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:28,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:29,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
    {
        id:30,
        url:'https://picsum.photos/200/300?random=',
        name:'forgoodCode'
    },
   
]
export default image